alias bunx 'vpx'
alias c 'clear'
alias grep 'grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn,.idea,.tox}'
alias npx 'vpx'
alias pbc 'pbcopy'
alias pbp 'pbpaste'
alias pn 'pnpm'
alias wr 'wrangler'
